package com.rookia.android.sejo


/**
 * Copyright (C) Rookia - All Rights Reserved
 *
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 *
 * Written by Roll <raulfeliz@gmail.com>, April 2020
 *
 *
 */

object Constants {

    //region PHONE NUMBER FORMAT
    const val SPANISH_PHONE_NUMBER_PREFIX = "+34"
    const val SPANISH_PHONE_NUMBER_MAX_LENGTH_WITH_SPACES = 11
    const val SPANISH_PHONE_NUMBER_MAX_LENGTH_WITHOUT_SPACES = 9

    const val SIGN_IN_PROCESS_HAS_VALIDATED_PHONE_TAG = "PREF_TAGS_SIGN_IN_PROCESS_HAS_VALIDATED_PHONE_TAG"
    const val SIGN_IN_PROCESS_VALIDATED_PHONE_NUMBER_TAG = "PREF_TAGS_SIGN_IN_PROCESS_VALIDATED_PHONE_NUMBER_TAG"
    const val SIGN_IN_PROCESS_VALIDATED_PHONE_PREFIX_TAG = "PREF_TAGS_SIGN_IN_PROCESS_VALIDATED_PHONE_PREFIX_TAG"
    const val SIGN_IN_PROCESS_SMS_TOKEN_TAG = "PREF_TAGS_SIGN_IN_PROCESS_SMS_TOKEN_TAG"
    const val SIGN_IN_PROCESS_HAS_SEEN_ONBOARDING_TAG = "PREF_TAGS_SIGN_IN_PROCESS_ALREADY_HAS_SEEN_ONBOARDING_TAG"
    const val SIGN_IN_PROCESS_IS_REGISTERED_TAG = "PREF_TAGS_SIGN_IN_PROCESS_IS_REGISTERED_TAG"
    const val SIGN_IN_PROCESS_PASSWORD_LENGTH_TAG = "PREF_TAGS_SIGN_IN_PROCESS_PASSWORD_LENGTH_TAG"
    const val SIGN_IN_PROCESS_NEEDS_USER_SELECTION_TAG = "PREF_TAGS_SIGN_IN_PROCESS_NEEDS_USER_SELECTION_TAG"
    const val SIGN_IN_PROCESS_PASSWORD_TAG = "PREF_TAGS_SIGN_IN_PROCESS_PASSWORD_TAG"
    const val SIGN_IN_PROCESS_USE_FINGERPRINT_TAG = "PREF_TAGS_SIGN_IN_PROCESS_USE_FINGERPRINT_TAG"

    const val SPANISH_PHONE_NUMBER_PATTERN_MATCHER_NINE_DIGITS = "(\\d{3})(\\d{3})(\\d{3})"
    const val SPANISH_PHONE_NUMBER_PATTERN_MATCHER_EIGHT_DIGITS = "(\\d{3})(\\d{3})(\\d{2})"
    const val SPANISH_PHONE_NUMBER_PATTERN_MATCHER_SEVEN_DIGITS = "(\\d{3})(\\d{3})(\\d{1})"
    const val SPANISH_PHONE_NUMBER_PATTERN_MATCHER_SIX_DIGITS = "(\\d{3})(\\d{3})"
    const val SPANISH_PHONE_NUMBER_PATTERN_MATCHER_FIVE_DIGITS = "(\\d{3})(\\d{2})"
    const val SPANISH_PHONE_NUMBER_PATTERN_MATCHER_FOUR_DIGITS = "(\\d{3})(\\d{1})"
    const val SPANISH_PHONE_NUMBER_PATTERN_REPLACEMENT_ONE_GROUP = "$1"
    const val SPANISH_PHONE_NUMBER_PATTERN_REPLACEMENT_TWO_GROUP = "$1 $2"
    const val SPANISH_PHONE_NUMBER_PATTERN_REPLACEMENT_THREE_GROUP = "$1 $2 $3"
    const val SPANISH_PHONE_NUMBER_START_PATTERN_MATCHER = "^[678].*"

    //endregion

    //region SMS CODE
    const val SMS_PIN_LENGTH = 6

    //endregion

    //region SERVER CONNECTION

    //endregion

    //region SERVER RESPONSE CODES
    const val   GENERAL_RESPONSE_OK = -1
    const val   GENERAL_RESPONSE_ERROR = 1
    const val   SMS_CODE_OK = 0
    const val   SMS_CODE_ERROR = 1
    const val   SMS_CODE_EXPIRED = 2
    //endregion
}